### ISSUE TITLE
information on numerical vs non-numerical features to `adata.var`

### ISSUE THREAD

**Issue by eroell** [theislab/ehrapy#620]
### Description of feature

**Background**
It is common to have numerical and categorical information in EHR data.

**Status**
ehrapy stores this information about features by having to entries in the `adata.uns` field, storing var_names of numerical and non-numerical features in `adata.uns['numerical_columns']` and `adata.uns['non_numerical_columns']`, respectively.

**Suggested change**
Rather than storing this per-variable information separately, storing it in adata.var.

**Benefits of this change**
- store this information together with other variable information seems intuitive
- reduce loading of `adata.uns`
- allow slicing along the `var` axis without interfering with subsequent methods (potentially most practically relevant)

**TODOs**

- [ ] Check this transformation is doable or whether it shows major drawbacks compared to storing in `adata.uns`
- [ ] Adapt the individual methods to use a new designated key of `adata.var`
- [ ] Backwards compatibility?
- [ ] Potentially new tests

**Comment by Zethson** [comment]
Great, thank you! I am down to making breaking changes but we should do it before the manuscript is out
