### ISSUE TITLE
Bias detection module

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#647]
### Description of feature

Pre-requisite: https://github.com/theislab/ehrapy/issues/637

This serves as a meta issue to collect ideas for a bias detection and mitigation module:

- [x] #645 
- [x] Missingness per feature -> missingno stuff
- [x] IQR outliers -> https://github.com/theislab/ehrapy/issues/648 for numerical data @Zethson 
- [x] value counts for categorical counts + warnings? Some things are already in tableone @Zethson 
- [x] sensitivity analysis - easy with ehrapy because the API is so easy @Zethson 
- [x] Imbalanced subsampling through https://imbalanced-learn.org/stable/index.html ? -> only the most important sampling features in ehrapy. Not the generation stuff. @eroell 
- [ ] Propensity score matching @Lilly-May 
- [x] standardized mean differences for numerical data @Lilly-May (#690)
- [x] Correlations between variables @Lilly-May (#690)
- [x] Feature importance -> requires target variable (only run if set) @Lilly-May (#690)
- [x] `generate_bias_report` that runs a lot of methods subsequently and summarizes things?!? @Lilly-May (#690)

**Comment by Lilly-May** [comment]
Regarding propensity score matching, we already have that implemented for causal inference with dowhy [here](https://github.com/theislab/ehrapy/blob/1b5165d925f87304948fffe9b76cc68669ee6ab2/ehrapy/tools/causal/_dowhy.py#L37). If we implement a causal discovery module (#619), implementing a propensity score matching algorithm would be important, but until then, I don't really see the need. However, please feel free to disagree!
Should we close this issue then?

**Comment by Zethson** [comment]
Yup! Let's close

May 4, 2024 12:18:43 PM Lilly May ***@***.***>:
